#ifndef DATA32_CHANNEL_DEF_H_
#define DATA32_CHANNEL_DEF_H_

#include "cmds.h"

#define DATA32_DATA_N_BYTES 4

typedef enum
{
	DATA32_REFRESH_DIVIDER
} DATA32_VARIABLES;

typedef enum
{
	DATA32_REQ_RESET_SETTINGS = COMMON_REQ_RESET_SETTINGS,	// NO payload
	DATA32_RES_RESET_SETTINGS = COMMON_RES_RESET_SETTINGS,	// NO payload
	DATA32_REQ_STATUS = COMMON_REQ_STATUS,					// NO payload
	DATA32_RES_STATUS = COMMON_RES_STATUS,					// TODO: some status msg
	DATA32_REQ_SET_VARIABLE = COMMON_REQ_SET_VARIABLE,		// SetMsg_t
	DATA32_RES_SET_VARIABLE = COMMON_RES_SET_VARIABLE,		// SetMsg_t
	DATA32_REQ_GET_VARIABLE = COMMON_REQ_GET_VARIABLE,		// GetMsg_t
	DATA32_RES_GET_VARIABLE = COMMON_RES_GET_VARIABLE,		// SetMsg_t

	DATA32_TOTAL_CMDS
} DATA32_CMDs;

#endif
