#ifndef OVERPRESSURE_CHANNEL_DEF_H
#define OVERPRESSURE_CHANNEL_DEF_H

#include "cmds.h"

typedef enum
{
    OVERPRESSURE_THRESHOLD,
    OVERPRESSURE_OPERATING_MODE,
} OVERPRESSURE_VARIABLES;

typedef enum
{
    OVERPRESSURE_REQ_RESET_SETTINGS = COMMON_REQ_RESET_SETTINGS,	// NO payload
    OVERPRESSURE_RES_RESET_SETTINGS = COMMON_RES_RESET_SETTINGS,	// NO payload
    OVERPRESSURE_REQ_STATUS = COMMON_REQ_STATUS,					// NO payload
    OVERPRESSURE_RES_STATUS = COMMON_RES_STATUS,					// TODO: some status msg
    OVERPRESSURE_REQ_SET_VARIABLE = COMMON_REQ_SET_VARIABLE,		// SetMsg_t
    OVERPRESSURE_RES_SET_VARIABLE = COMMON_RES_SET_VARIABLE,		// SetMsg_t
    OVERPRESSURE_REQ_GET_VARIABLE = COMMON_REQ_GET_VARIABLE,		// GetMsg_t
    OVERPRESSURE_RES_GET_VARIABLE = COMMON_RES_GET_VARIABLE,		// SetMsg_t

    OVERPRESSURE_TOTAL_CMDS
} OVERPRESSURE_CMDs;

#endif //OVERPRESSURE_CHANNEL_DEF_H
